### PR TITLE
Feature add review endpoints v0.81

### PR DESCRIPTION
**Pull request by DarthRevan77797**
Added temporary h2 database to test endpoints
For now disabled spring security for /review/** endpoints

Later on h2 should be change to proper database postgres  (change application.properties)

### CODE REVIEW

**Comment by Nekio21** [comment]
Maybe, I did something bad, but aplication returns erorrs(Factory method 'userDetailsService' threw exception with message: rawPassword cannot be null)

**Comment by ThePapiok** [comment]
> Maybe, I did something bad, but aplication returns erorrs(Factory method 'userDetailsService' threw exception with message: rawPassword cannot be null)

I think you should read readme

**Comment by Nekio21** [comment]
> > Maybe, I did something bad, but aplication returns erorrs(Factory method 'userDetailsService' threw exception with message: rawPassword cannot be null)
> 
> I think you should read readme

**Review by Nekio21 — APPROVED** [review]
Great Job, You are the best

**Pull request merged**
